### ISSUE TITLE
"gui" command not shown in help

### ISSUE THREAD

**Issue by winbamstudios** [9xbt/iDOS#12]
The GUI command is not shown in the help menu. I'd recommend fixing this so new users don't lose their mind trying to launch the experimental GUI.

**Comment by 9xbt** [comment]
Hey, sorry for not seeing your issue. I'm gonna fix it this night.

**Comment by 9xbt** [comment]
Nvm @Winksplorer made a pr fixing it. Imma close this now since its fixed
